### ISSUE TITLE
Code Review: Umeyyan Hawley, 26794347

### ISSUE THREAD

**Issue by Umeyyan** [BeansAreOk/CMP1903M-A01-2223#3]
I believe your constructor method for your Card class requires some for of Data validation such as a range check to ensure the value parameter isn't greater than 13 and the suit isn't greater than 4.

I'm assuming the DealCards class is not supposed to be in the folder as it is pretty much empty so that should be deleted. 

Your shuffling algorithms seem pretty good and look like they'd run perfectly on paper. I also really like how you commented on your code, it's simple and states what each section of the code is for. Well done.

One last point is that you forgot to start an instance of the testing class in the Program class and this would stop your code from running at all.

**Comment by BeansAreOk** [comment]
Thanks for your review, I have amended pretty much all of these mistakes except the range check since, as I do not believe it is necessary to put a range check in for something that to my understanding is unable to go higher than the values I provided.
